-   repo: https://gitlab.com/pycqa/flake8
    rev: ''
    hooks:
    -   id: flake8
-   repo: https://github.com/timothycrosley/isort
    rev: ''
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.7
