channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - nose
  - pytest
  - setuptools
  - ipython
  - git
  - unyt
  - Cython
  - sympy
  - fastcache
  - h5py
  - matplotlib=3.1.3
  - mock
  - pandas
  - cartopy
  - conda-build
  - pooch
  - pyyaml
  - nose-timer
  - pykdtree
